name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Surveillez la branche principale
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Adaptez selon vos besoins

      # 3. Installer les dépendances et tester le backend
      - name: Install & Test Backend
        working-directory: ./backend
        run: |
          npm install

      # 4. Installer les dépendances et tester le frontend
      - name: Install & Test Frontend
        working-directory: ./frontend
        run: |
          npm install

      # 5. Build le frontend
      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

  cd:
    name: Deploy
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Déploiement : Adaptez cette étape en fonction de votre cible
      - name: Deploy to Server
        run: |
          echo "Déploiement sur le serveur en cours..."
          # Ajoutez votre script de déploiement ici (SSH, FTP, Docker, etc.)
